#!/usr/bin/env bash
# run as root
set -euo pipefail

SCRIPT_DIR=$(dirname "$(realpath "$0")")
cd "$SCRIPT_DIR"

# Which type of install?
# First choice: vm or hardware
echo "Choose one:"
select hardware in "vm" "hardware"; do
  [[ -n $hardware ]] && break
  echo "Invalid choice. Please select 1 for vm or 2 for hardware."
done

# extra choice: laptop or bluetooth or none
if [[ "$hardware" == "hardware" ]]; then
  echo "Choose one:"
  select extra in "laptop" "bluetooth" "none"; do
    [[ -n $extra ]] && break
    echo "Invalid choice."
  done
else
  extra="none"
fi

# Which type of packages?
# Main package selection
case "$hardware" in
vm)
  sed -n '1p' pkgs.txt | tr ' ' '\n' | grep -v '^$' >>pkglist.txt
  ;;
hardware)
  sed -n '1p;2p' pkgs.txt | tr ' ' '\n' | grep -v '^$' >>pkglist.txt
  ;;
esac

# For hardware:max, add lines 5 and/or 6 based on $extra
if [[ "$hardware" == "hardware" ]]; then
  case "$extra" in
  laptop)
    sed -n '3p;4p' pkgs.txt | tr ' ' '\n' | grep -v '^$' >>pkglist.txt
    ;;
  bluetooth)
    sed -n '3p' pkgs.txt | tr ' ' '\n' | grep -v '^$' >>pkglist.txt
    ;;
  none) ;;
  esac
fi

# Package installation apt
# apt update
xargs -a pkglist.txt apt install -y

# Tlp setup
# Robust detection: prefer explicit pstate driver dirs if present, fallback to scaling_driver text
scaling_f="/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver"
pstate_supported=false
driver=""
if [ -d /sys/devices/system/cpu/intel_pstate ]; then
  driver="intel_pstate"
  pstate_supported=true
elif [ -d /sys/devices/system/cpu/amd_pstate ] || [ -d /sys/devices/system/cpu/amd-pstate ]; then
  # kernel docs and kernels may expose amd_pstate/amd-pstate; accept either
  driver="amd_pstate"
  pstate_supported=true
elif [ -r "$scaling_f" ]; then
  # fallback: read scaling_driver and normalise
  rawdrv=$(cat "$scaling_f" 2>/dev/null || true)
  case "$rawdrv" in
  *intel*)
    driver="intel_pstate"
    pstate_supported=true
    ;;
  *amd*)
    driver="amd_pstate"
    pstate_supported=true
    ;;
  *) driver="$rawdrv" ;;
  esac
fi

# Kernel parameter to encourage pstate driver mode on next boot (set only when pstate is supported)
pstate_param=""
if [ "$pstate_supported" = true ]; then
  if [ "$driver" = "intel_pstate" ]; then
    # prefer 'active' for AC; we'll keep TLP switching to 'passive' on BAT to allow schedutil there.
    pstate_param="intel_pstate=active"
  elif [ "$driver" = "amd_pstate" ]; then
    # amd_pstate supports active/passive/guided depending on kernel; active is a reasonable default.
    pstate_param="amd_pstate=active"
  fi
fi

# Write base TLP config (safe defaults; adjust values below if you want more aggressive perf)
if [[ "$extra" == "laptop" ]]; then
  cat >/etc/tlp.conf <<EOF
# Generated by installer - baseline TLP config
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=low-power

# PCIe ASPM: prefer default on AC (don't force performance), aggressive on battery
PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersupersave

USB_AUTOSUSPEND=1
USB_EXCLUDE_BTUSB=0
USB_EXCLUDE_PHONE=1

# Runtime PM (use new name)
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
RUNTIME_PM_DRIVER_DENYLIST="amdgpu nouveau nvidia"

WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1

DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"

# Per-disk IO scheduler: use mq-deadline as safe default (leave kernel default with 'keep')
DISK_IOSCHED="none mq-deadline kyber bfq"

SATA_LINKPWR_ON_AC=max_performance
SATA_LINKPWR_ON_BAT=min_power

# Charging thresholds (only functional if tlp-rdw and hardware support)
START_CHARGE_THRESH_BAT0=40
STOP_CHARGE_THRESH_BAT0=80
EOF

  # CPU-specific settings by driver
  if [ "$driver" = "intel_pstate" ]; then
    # Use 'active' for AC (intel internal algorithms), use 'passive' on BAT so schedutil can be selected
    cat >>/etc/tlp.conf <<EOF
# Intel pstate tuning
CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=passive
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=schedutil
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF

  elif [ "$driver" = "amd_pstate" ]; then
    # For AMD: prefer active when the new energy/CPP features exist, otherwise fall back to using schedutil
    if [ -f /sys/devices/system/cpu/cpufreq/policy0/energy_performance_preference ]; then
      cat >>/etc/tlp.conf <<EOF
# AMD pstate with energy perf preference support
CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=active
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF
    else
      cat >>/etc/tlp.conf <<EOF
# AMD pstate older kernels - keep schedutil
CPU_DRIVER_OPMODE_ON_AC=passive
CPU_DRIVER_OPMODE_ON_BAT=passive
CPU_SCALING_GOVERNOR_ON_AC=schedutil
CPU_SCALING_GOVERNOR_ON_BAT=schedutil
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF
    fi

  else
    # Generic fallback: use schedutil both AC/BAT
    cat >>/etc/tlp.conf <<EOF
# Generic CPUfreq fallback
CPU_DRIVER_OPMODE_ON_AC=passive
CPU_DRIVER_OPMODE_ON_BAT=passive
CPU_SCALING_GOVERNOR_ON_AC=schedutil
CPU_SCALING_GOVERNOR_ON_BAT=schedutil
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF
  fi
fi

# Boot Manager setup
echo "timeout 3" >>/boot/efi/loader/loader.conf
echo "editor no" >>/boot/efi/loader/loader.conf
if [ -n "$pstate_param" ]; then
  for f in /boot/efi/loader/entries/*; do
    sed -n 's/^options[[:space:]]\+//p' "$f" | grep -Fq "fsck.repair=yes zswap.enabled=0" && continue
    sed -i "/^options[[:space:]]\+/ s/$/ fsck.repair=yes zswap.enabled=0/p" "$f"
    [ -f "$f" ] || continue
    sed -n 's/^options[[:space:]]\+//p' "$f" | grep -Fq "$pstate_param" && continue
    sed -i "/^options[[:space:]]\+/ s/$/ $pstate_param/p" "$f"
  done
fi

# Sudo Configuration
echo "%wheel ALL=(ALL) ALL" >/etc/sudoers.d/wheel
echo "Defaults timestamp_timeout=-1" >/etc/sudoers.d/timestamp
echo "Defaults pwfeedback" >/etc/sudoers.d/pwfeedback
echo 'Defaults env_keep += "SYSTEMD_EDITOR XDG_RUNTIME_DIR WAYLAND_DISPLAY DBUS_SESSION_BUS_ADDRESS WAYLAND_SOCKET"' >/etc/sudoers.d/wayland
chmod 440 /etc/sudoers.d/*
if [[ "$hardware" == "hardware" ]]; then
  usermod -aG libvirt,kvm,lpadmin piyush
fi
usermod -aG sudo,adm,cdrom,plugdev,video,audio,input,netdev,docker piyush

# UFW setup
# ufw limit 22/tcp              # ssh
ufw allow from 192.168.0.0/24 to any port 22 proto tcp #ssh local
# ufw allow 80/tcp              # http
# ufw allow 443/tcp             # https
ufw allow from 192.168.0.0/24 #lan
ufw deny 631/tcp              # cups stuff
ufw allow in on virbr0 to any port 67 proto udp
ufw allow out on virbr0 to any port 68 proto udp
ufw allow in on virbr0 to any port 53
ufw allow out on virbr0 to any port 53
ufw default allow routed
ufw default deny incoming
ufw default allow outgoing
ufw enable
ufw logging on
sed -i -E 's/^#?\s*interface=.*/interface=virbr0/; s/^#?\s*bind-interfaces.*/bind-interfaces/' /etc/dnsmasq.conf

# apparmour stuff
# aa-enforce /etc/apparmor.d/Discord
# aa-enforce /etc/apparmor.d/steam
# aa-enforce /etc/apparmor.d/signal-desktop
# aa-enforce /etc/apparmor.d/firefox
# aa-enforce /etc/apparmor.d/flatpak
# aa-enforce /etc/apparmor.d/loupe

tee /etc/sysctl.d/99-hardening.conf >/dev/null <<'EOF'
# networking
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.ip_forward = 0

# kernel hardening
kernel.kptr_restrict = 2

# file protections
fs.protected_fifos = 2

# bpf jit harden (if present)
net.core.bpf_jit_harden = 2
EOF

# A anacron job
echo "30 5 trash-empty-job su - piyush -c '$(which trash-empty)'" >>/etc/anacrontab

sh <(curl -L https://nixos.org/nix/install) --daemon --yes
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y org.gtk.Gtk3theme.Adwaita-dark
flatpak override --user --env=GTK_THEME=Adwaita-dark --env=QT_STYLE_OVERRIDE=Adwaita-Dark
su - piyush -c '
  mkdir -p ~/Downloads ~/Desktop ~/Public ~/Templates ~/Videos ~/Pictures/Screenshots/temp ~/.config
  mkdir -p ~/Documents/personal/default ~/Documents/projects/work ~/Documents/projects/personal ~/Documents/personal/wiki
  mkdir -p ~/.local/bin ~/.cache/cargo-target ~/.local/state/bash ~/.local/state/zsh ~/.local/share/wineprefixes
  touch ~/.local/state/bash/history ~/.local/state/zsh/history
  echo todo.txt > ~/Documents/personal/wiki/index.txt
  echo 1. Write some todos > ~/Documents/personal/wiki/todo.txt

  git clone https://github.com/zedonix/scripts.git ~/Documents/personal/default/scripts
  git clone https://github.com/zedonix/dotfiles.git ~/Documents/personal/default/dotfiles
  git clone https://github.com/zedonix/debsetup.git ~/Documents/personal/default/debsetup
  git clone https://github.com/zedonix/notes.git ~/Documents/personal/default/notes
  git clone https://github.com/zedonix/GruvboxGtk.git ~/Documents/personal/default/GruvboxGtk
  git clone https://github.com/zedonix/GruvboxQT.git ~/Documents/personal/default/GruvboxQT

  cp ~/Documents/personal/default/dotfiles/.config/sway/archLogo.png ~/Pictures/
  cp ~/Documents/personal/default/dotfiles/.config/sway/debLogo.png ~/Pictures/
  cp ~/Documents/personal/default/dotfiles/pics/* ~/Pictures/
  ln -sf ~/Documents/personal/default/dotfiles/.bashrc ~/.bashrc
  ln -sf ~/Documents/personal/default/dotfiles/.zshrc ~/.zshrc
  ln -sf ~/Documents/personal/default/dotfiles/.XCompose ~/.XCompose

  for link in ~/Documents/personal/default/dotfiles/.config/*; do
    ln -sf $link ~/.config/
  done
  for link in ~/Documents/personal/default/dotfiles/copy/*; do
    cp -r $link ~/.config/
  done
  for link in ~/Documents/personal/default/scripts/bin/*; do
    ln -sf $link ~/.local/bin/
  done
  git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
  zoxide add /home/piyush/Documents/personal/default/debsetup
  source ~/.bashrc

  # Iosevka
  cd ~/Downloads/
  mkdir -p ~/.local/share/fonts/iosevka
  cd ~/.local/share/fonts/iosevka
  curl -LO https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTerm.zip
  unzip IosevkaTerm.zip
  rm IosevkaTerm.zip

  rustup default stable
  docker create --name omni-tools --restart no -p 1024:80 iib0011/omni-tools:latest
  docker create --name bentopdf --restart no -p 1025:8080 bentopdf/bentopdf:latest
  docker create --name convertx --restart no -p 1026:3000 -v ./data:/app/data ghcr.io/c4illin/convertx
'

if [[ "$hardware" == "hardware" ]]; then
  su - piyush -c '
    flatpak install -y flathub com.github.wwmm.easyeffects
    flatpak install -y flathub no.mifi.losslesscut
    flatpak install -y flathub com.obsproject.Studio
  '
fi
if [[ "$extra" == "laptop" ]]; then
  su - piyush -c '
    flatpak install -y flathub com.github.d4nj1.tlpui
    flatpak install -y nl.brixit.powersupply
  '
fi

# Root dots
mkdir -p ~/.config ~/.local/state/bash ~/.local/state/zsh
echo '[[ -f ~/.bashrc ]] && . ~/.bashrc' >~/.bash_profile
touch ~/.local/state/zsh/history ~/.local/state/bash/history
ln -sf /home/piyush/Documents/personal/default/dotfiles/nix.conf /etc/nix/nix.conf
ln -sf /home/piyush/Documents/personal/default/dotfiles/.bashrc ~/.bashrc
ln -sf /home/piyush/Documents/personal/default/dotfiles/.zshrc ~/.zshrc
ln -sf /home/piyush/Documents/personal/default/dotfiles/.config/starship.toml ~/.config
ln -sf /home/piyush/Documents/personal/default/dotfiles/.config/nvim/ ~/.config

source ~/.bashrc
systemctl restart nix-daemon

su - piyush -c '
  nix profile add \
    nixpkgs#hyprpicker \
    nixpkgs#bemoji \
    nixpkgs#yazi \
    nixpkgs#lazydocker \
    nixpkgs#cliphist \
    nixpkgs#wl-clip-persist \
    nixpkgs#upscaler \
    nixpkgs#onlyoffice-desktopeditors \
    nixpkgs#wayland-pipewire-idle-inhibit \
    nixpkgs#networkmanager_dmenu \
    nixpkgs#newsraft \
    nixpkgs#go \
    nixpkgs#uv \
    nixpkgs#opencode \
    nixpkgs#javaPackages.compiler.temurin-bin.jre-17
    # nixpkgs#losslesscut-bin
  # nix build nixpkgs#opencode --no-link --no-substitute
'
for u in $(getent passwd | awk -F: '/^nixbld[0-9]+/ {print $1}'); do
  userdel -r "$u"
done

corepack enable
corepack prepare pnpm@latest --activate
npm install -g tree-sitter-cli

# ly
curl -LO https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz
tar -xf zig-x86_64-linux-0.15.1.tar.xz
mv zig-x86_64-linux-0.15.1 /opt/zig
ln -sf /opt/zig/zig /usr/local/bin/zig
cd /root
tag=$(git ls-remote --tags --refs https://codeberg.org/fairyglade/ly.git | awk -F/ '{print $NF}' | sed 's/\^{}//' | sort -V | tail -n1)
git clone --depth 1 --branch "$tag" https://codeberg.org/fairyglade/ly.git
cd ly
zig build -Dinit_system=systemd -Denable_x11_support=false --verbose
zig build installexe -Dinit_system=systemd
rm -rf /opt/zig
rm -f /usr/local/bin/zig

# ananicy-cpp
git clone --depth 1 https://gitlab.com/ananicy-cpp/ananicy-cpp.git
cd ananicy-cpp
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_SYSTEMD=ON -DUSE_BPF_PROC_IMPL=ON -DWITH_BPF=ON
cmake --build build --target ananicy-cpp
cmake --install build --component Runtime

# neovim
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
rm -rf /opt/nvim-linux-x86_64
tar -C /opt -xzf nvim-linux-x86_64.tar.gz

# ly config
# -e 's/^bigclock *= *.*/bigclock = en/' \
sed -i \
  -e 's/^allow_empty_password *= *.*/allow_empty_password = false/' \
  -e 's/^clear_password *= *.*/clear_password = true/' \
  -e 's/^clock *= *.*/clock = %a %d\/%m %H:%M/' \
  /etc/ly/config.ini

# Setup gruvbox theme
THEME_SRC="/home/piyush/Documents/personal/default/GruvboxQT"
THEME_DEST="/usr/share/Kvantum/Gruvbox"
mkdir -p "$THEME_DEST"
cp "$THEME_SRC/gruvbox-kvantum.kvconfig" "$THEME_DEST/Gruvbox.kvconfig"
cp "$THEME_SRC/gruvbox-kvantum.svg" "$THEME_DEST/Gruvbox.svg"

THEME_SRC="/home/piyush/Documents/personal/default/GruvboxGtk"
THEME_DEST="/usr/share"
cp -r "$THEME_SRC/themes/Gruvbox-Material-Dark" "$THEME_DEST/themes"
cp -r "$THEME_SRC/icons/Gruvbox-Material-Dark" "$THEME_DEST/icons"

# Anancy-cpp rules
git clone --depth=1 https://github.com/RogueScholar/ananicy.git
git clone --depth=1 https://github.com/CachyOS/ananicy-rules.git
mkdir -p /etc/ananicy.d/roguescholar /etc/ananicy.d/zz-cachyos
cp -r ananicy/ananicy.d/* /etc/ananicy.d/roguescholar/
cp -r ananicy-rules/00-default/* /etc/ananicy.d/zz-cachyos/
cp -r ananicy-rules/00-types.types /etc/ananicy.d/zz-cachyos/
cp -r ananicy-rules/00-cgroups.cgroups /etc/ananicy.d/zz-cachyos/
tee /etc/ananicy.d/ananicy.conf >/dev/null <<'EOF'
check_freq = 15
cgroup_load = false
type_load = true
rule_load = true
apply_nice = true
apply_latnice = true
apply_ionice = true
apply_sched = true
apply_oom_score_adj = true
apply_cgroup = true
loglevel = info
log_applied_rule = false
cgroup_realtime_workaround = false
EOF

# Firefox policy
mkdir -p /etc/firefox/policies
ln -sf "/home/piyush/Documents/personal/default/dotfiles/policies.json" /etc/firefox/policies/policies.json

# zram config
# Get total memory in MiB
TOTAL_MEM=$(awk '/MemTotal/ {print int($2 / 1024)}' /proc/meminfo)
ZRAM_SIZE=$((TOTAL_MEM / 2))

# Create zram config
mkdir -p /etc/systemd/zram-generator.conf.d
{
  echo "[zram0]"
  echo "zram-size = ${ZRAM_SIZE}"
  echo "compression-algorithm = zstd"
  echo "swap-priority = 100"
  echo "fs-type = swap"
} >/etc/systemd/zram-generator.conf.d/00-zram.conf

# Services
# rfkill unblock bluetooth
# modprobe btusb || true
if [[ "$hardware" == "hardware" ]]; then
  systemctl enable fstrim.timer acpid libvirtd.socket cups ipp-usb docker.socket libvirtd.service
  systemctl disable docker.service dnsmasq
fi
if [[ "$extra" == "laptop" || "$extra" == "bluetooth" ]]; then
  systemctl enable bluetooth
fi
if [[ "$extra" == "laptop" ]]; then
  systemctl enable tlp
fi
systemctl enable ly@tty2 ananicy-cpp
systemctl enable NetworkManager NetworkManager-dispatcher ufw
systemctl mask systemd-rfkill systemd-rfkill.socket apparmor
systemctl disable NetworkManager-wait-online.service getty@tty2.service apparmor

# Cleaning post setup
apt remove --purge -y ccache ninja-build gettext vim-common vim-tiny libspdlog-dev nlohmann-json3-dev libfmt-dev libpipewire-0.3-dev libxcb-xkb-dev libpam0g-dev cmake g++ libsystemd-dev libsqlite3-dev libexpat1-dev libgumbo-dev libcurl4-openssl-dev pkg-config libbpf-dev libelf-dev clang bpftool dwarves zlib1g-dev nano vlc
apt autoremove --purge -y
apt clean
